const image=document.createElement("img");
image.src="https://rukminim2.flixcart.com/image/480/640/xif0q/book/n/p/z/physics-text-book-part-1-for-class-12-board-book-1-january-2024-original-imagysdgunh6acem.jpeg?q=90";
image.width=200;
image.height=200;
image.alt="Book Image";
const h3=document.createElement("h3");
h3.innerText="Title: Physics";
const h4=document.createElement("h4");
h4.innerText="Price: $400";
const button=document.createElement("button");
button.innerText="Buy Now";
const child=document.createElement("div");
child.className="card";
child.appendChild(image);
child.appendChild(h3);
child.appendChild(h4);
child.appendChild(button);
const parent=document.getElementById("root");
parent.appendChild(child);